openapi: 3.1.0
info:
  title: API仕様（SoT）
  version: 0.1.0
servers:
  - url: https://api.example.com
    description: production
  - url: https://stg.api.example.com
    description: staging
paths:
  /health:
    get:
      summary: Health Check
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok

